- name: Variables
  hosts: local
  connection: local
  vars: 
   COURSE: devops
   TRAINER: sivakumar
   DURATION: 120 hrs
  tasks:
  - name: print the Variables
    ansible.builtin.debug:
     msg: "Course is {{COURSE}}, Trainer is {{TRAINER}, Duration is {{DURATION}}"