- name: Variables
  hosts: local
  connection: local
  vars: #Global variables
   COURSE: devops
   TRAINER: sivakumar
   DURATION: 120hrs
  tasks:
  - name: print the Variables
    vars: #local variables
     COURSE: ansible
    ansible.builtin.debug:
     msg: "Course is {{COURSE}} Duration is {{DURATION}} Trainer is {{TRAINER}}"
  - name: print the Variables
    ansible.builtin.debug:
     msg: "Course is {{COURSE}} Duration is {{DURATION}} Trainer is {{TRAINER}}"
  