- name: printing the names using loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ item }}"
    loop:
    - Ramesh
    - Suesh
    - Mahesh