#!/bin/bash

- name: loops
  hosts: web
  tasks:
  - name: print the names
    ansible.builtin.debug:
     msg: "Hello {{ items }}"
    loop:
    - RUSHHAV
    - BHARGAV
    - LALITH
    - MOHAN
    - ADITHYA