- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variables
    ansible.builtin.debug:
      msg: "hello {{ person | default('Rushhav') }}"
    
  - name: Convert string to list
    vars:
      fruits: "apple, banana, orange" #string
    ansible.builtin.debug:
      msg: "fruits are {{ fruits | split(',') }}"
    
  - name: Convert map to list
    vars:
      course: #map
        name: Devops
        duration: 120 hrs
        trainer: siva
    ansible.builtin.debug:
      msg: "course info: {{ course | dict2items }}"

  - name: convert list to map
    vars:
      course:
        - { 'key': 'name', 'value': devops }
        - { 'key': 'duration', 'value': 120 }
        - { 'key': 'trainer', 'value':siva }
    ansible.builtin.debug:
      msg: "Course info: {{ course | items2dict }}"

  - name: convert upper to lower
    tags:
    - upper to lower
    vars:
      name: sIVA
    ansible.builtin.debug:
      msg: "hello {{ name | lower }}"

  - name: convert lower to upper
    vars:
      name: Rushhav
    ansible.builtin.debug:
      msg: "hello {{ name | upper }}"

  - name: print max and min
    vars:
      numbers: [13,24,554,21321]
    ansible.builtin.debug:
      msg: "Min is: {{ numbers | min }}, Max is {{ numbers | max }}"

  - name: check ipaddress is valid or not
    vars:
      ip: "172.31.4.148"
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.ipaddr }}"